### ISSUE TITLE
Notifications are gone 

### ISSUE THREAD

**Issue by turbomoxxi** [mastodon/mastodon-android#888]
This might be an issue related to the new grouped notifications but on my Pixel 8 pro, Mastodon mobile has stopped pushing notifications for a little over a week. Same thing is true for Fedilab by the way. Mastodon mobile and Fedilab will stop pushing notifications periodically and usually start again after a while, but this time they've both stopped at the same time.

**Comment by turbomoxxi** [comment]
Ah yes sorry, I'm on mastodon.social

**Comment by JohnySeven** [comment]
I do have the same issue. I am hosting my own instance. What should I check to see if any push notification is being sent by the server?

**Comment by jotaluissoy** [comment]
Hello everybody. It seems it is related to this legacy API deprecation ( https://firebase.google.com/docs/cloud-messaging/migrate-v1?hl=en&authuser=0 ) and needs updating. (See text from this screen
<img width="868" alt="2922b387c340f6df" src="https://github.com/user-attachments/assets/c80ad950-4b90-4bb4-a9bd-17297267dce0">
shot)

(I have already posted the issue to Mastodon web)

**Comment by grishka** [comment]
![FD9sV40VQAw72Qu](https://github.com/user-attachments/assets/3f545b22-2fa0-4dc0-ac18-1b85226b48d9)

**Comment by renchap** [comment]
Here is the PR switching the relay server to the new Firebase API: https://github.com/mastodon/webpush-fcm-relay/pull/5

We are testing it today.

**Comment by renchap** [comment]
We updated our Firebase relay to use the new API, and notifications should be working again.

**Comment by JohnySeven** [comment]
It's working. Thank you, guys! 👌

**Comment by turbomoxxi** [comment]
Still not working over here and also on sunny.garden with the same app and phone. I guess it'll take a couple more days?

**Comment by stephanborn** [comment]
For me it is still not working. I am on mastodon.world
Was this a server update? The app is version 2.6.1 on Android 14

**Comment by turbomoxxi** [comment]
I just confirmed that notifications are working on my old Pixel 5 and still nothing on my Pixel 8 pro. Fedilab also isn't pushing notifications to my Pixel 8 pro.

**Comment by stephanborn** [comment]
Is it possible to create a debug log which can be sent here?

**Comment by stephanborn** [comment]
Could it be that phone needs to be restarted? Mine is running over 70 hours, but your fix was done yesterday. I will give it a try

**Comment by turbomoxxi** [comment]
Just restarted this morning with a system update. I confirmed with a new post that notifications were going through on the Pixel 5 but not 8.

**Comment by stephanborn** [comment]
BTW: might be related to this issue:
https://github.com/mastodon/mastodon-android/issues/407

The same happen for me: mastodon has the permissions for notifications when I look at the app's settings - but is not listed on the view will all the apps allowed/ not allowed to send notifications

**Comment by turbomoxxi** [comment]
Weird, it's listed on my phone 

![Screenshot_20240912-121542.png](https://github.com/user-attachments/assets/268ce87b-6b5e-410a-937d-d8951196a533)

**Comment by grishka** [comment]
"Recent" only shows apps that posted notifications in the last 7 days.

**Comment by turbomoxxi** [comment]
Weird, it's listed on my phone 

![Screenshot_20240912-121542.png](https://github.com/user-attachments/assets/268ce87b-6b5e-410a-937d-d8951196a533)

**Comment by turbomoxxi** [comment]
Yes, what's odd is that I've used both apps less than a minute ago so their math ain't mathing.

**Comment by turbomoxxi** [comment]
Additional information: it doesn't happen often but once in a while, the new interactions (without notifications) will appear as seen in the notifications tab. Meaning: I know those are new likes or boosts since last time I opened the app but Mastodon for Android shows all of them as read. It's happening right now - it should show new notifications:

![Screenshot_20240912-123724.png](https://github.com/user-attachments/assets/b3c85a93-3ad4-4dea-ba2d-8b502d9a4db3)

I'm trying to get people to interact more to get more notifications but I fear I'll need to bring out the big guns and post a cute photo of Moxxi

**Comment by grishka** [comment]
Yes, that part breaks sometimes because the current notifications API makes counting unread notifications extremely fragile (you need the notification list itself and the marker, then you find the offset of the marker into the list). Upcoming Mastodon 4.3 introduces a new notifications API that solves this problem so this will work better in a future release.

(it might also be my bug though...)

**Comment by turbomoxxi** [comment]
Ah then, unrelated. Welp.

**Comment by turbomoxxi** [comment]
Additional info: It does seem to be server-dependent. I receive notifications from fosstodon.org but still not from mastodon.social or sunny.garden.

**Comment by grishka** [comment]
It would probably help to refresh the FCM token, but there isn't a way to trigger this from the UI 🙈
You can only do it by clearing the app data. Or wait for the next update, the token is also refreshed on app updates.

**Comment by turbomoxxi** [comment]
Okay! Clearing the data worked! I'll do the same with Fedilab. Mystery
solved!
